---
title: "SRI Epidemic Model"
output: html_notebook
---
```{r}
install.packages("deSolve", repos="http://R-Forge.R-project.org")
## Load deSolve package
library(deSolve)
#these libraries need to be loaded
library(utils)
library(httr)
library(R0)
```
Download data from the European Centre for Disease Prevention and Control[R Markdown](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide)

```{r}
#download the dataset from the ECDC website to a local temporary file
GET("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", authenticate(":", ":", type="ntlm"), write_disk(tf <- tempfile(fileext = ".csv")))

#read the Dataset sheet into “R”. The dataset will be called "data".
data <- read.csv(tf)
covid_worldwide <- data.frame(data)
head(covid_worldwide, 50)
glimpse(covid_worldwide)
```

```{r}
covid_mexico <- filter(covid_worldwide, countriesAndTerritories  == "Mexico")
infected_mex <- sum(as.numeric(covid_mexico$cases))
gamma = 1/87
print(gamma)
```


```{r}

## Create an SIR function
sir <- function(time, state, parameters) {

  with(as.list(c(state, parameters)), {

    dS <- -beta * S * I
    dI <-  beta * S * I - gamma * I
    dR <-                 gamma * I

    return(list(c(dS, dI, dR)))
  })
}

### Set parameters
## Proportion in each compartment: Susceptible 0.999999, Infected 0.000001, Recovered 0
init       <- c(S = 0.999999 , I = 0.000001, R = 0.0)
## beta: infection parameter; gamma: recovery parameter
parameters <- c(beta = 2.15
                , gamma = 0.14286)
## Time frame
times      <- seq(0, 90, by = 1)

## Solve using ode (General Solver for Ordinary Differential Equations)
out <- ode(y = init, times = times, func = sir, parms = parameters)
## change to data frame
out <- as.data.frame(out)
## Delete time variable
out$time <- NULL
## Show data
head(out, 10)

## Plot
matplot(x = times, y = out, type = "l",
        xlab = "Time", ylab = "Susceptible and Recovered", main = "SIR Model",
        lwd = 1, lty = 1, bty = "l", col = 2:4)

## Add legend
legend(40, 0.7, c("Susceptible", "Infected", "Recovered"), pch = 1, col = 2:4, bty = "n")
```

